<template>
  <v-app dark>
    <!--navigation menu-->
    <v-navigation-drawer v-model="drawer" fixed app>
      <div class="navmenu d-flex flex-column">
        <v-list>
          <v-list-item
            v-for="(page, i) in pages"
            :key="i"
            :to="page.to"
            router
            exact
          >
            <v-list-item-action>
              <v-icon :icon="page.icon" size="16" />
              <v-list-item-title class="ml-2 text-caption" v-text="page.title" />
            </v-list-item-action>
          </v-list-item>
        </v-list>

        <v-divider vertical/>

        <!--privacy policy-->
        <div class="text-caption text-center pa-4">
          <v-dialog>
            <template v-slot:activator="{ props }">
              <v-btn class="text-caption" v-bind="props" text="Privacy Policy" />
            </template>
            <template v-slot:default="{ isActive }">
              <v-card>
                <v-card-title class="text-overline">Privacy Policy for Website Analytics</v-card-title>
                <v-card-text class="text-body-2">
                  <p class="mb-2">Our website uses Google Analytics, a web analytics service provided by Google. Google Analytics uses cookies, which are small text files placed on your computer, to help the website analyze how users interact with the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google.</p>
                  <p class="mb-2">The data collected by Google Analytics is anonymous and does not personally identify you. It is used for the sole purpose of analyzing website traffic and user interaction patterns.</p>
                  <p class="mb-2">You have the option to refuse the collection of data by Google Analytics by disabling cookies in your browser settings. Please check your browser’s settings to manage your cookie preferences.</p>
                  <p class="mb-2">For more information on how Google uses data when you use our site and how to opt out, please visit Google Analytics Terms of Service and the Google Privacy & Terms page.</p>
                </v-card-text>
                <v-card-actions>
                  <v-spacer></v-spacer>
                  <v-btn class="text-overline" text="Close" @click="isActive.value=false" />
                </v-card-actions>
              </v-card>
            </template>
          </v-dialog>
        </div>

      </div>
    </v-navigation-drawer>

    <!--title bar-->
    <v-app-bar fixed app >
      <v-app-bar-nav-icon @click.stop="drawer = !drawer" />
    </v-app-bar>

    <!--article-->
    <v-main>
      <v-container fill-height>
        <slot />
      </v-container>
    </v-main>

    <!--footer-->
    <v-footer app class="justify-center" >
      <span class="text-caption">&copy; {{ new Date().getFullYear() }} S.Nakano</span>
    </v-footer>

  </v-app>
</template>


<script lang="ts" setup>
import { ref } from 'vue'
const drawer = ref(false)

const pages = [
  {
    icon: 'mdi-apps',
    title: 'Home',
    to: '/'
  },
  {
    icon: 'mdi-notebook',
    title: 'Posts',
    to: '/posts'
  }
];

const siteTitle = 'sumeshi.github.io';
useHead({
  titleTemplate: (pageTitle) => {
    return pageTitle ? `${pageTitle} - ${siteTitle}` : siteTitle;
  }
})
</script>

<style lang="scss" scoped>
.navmenu {
  height: 100vh;
  max-height: 100vh;
}
.nuxt {
  animation: fadeIn 0.3s ease 0s 1 normal;
}

@keyframes fadeIn {
  0% {opacity: 0}
  100% {opacity: 1}
}
</style>
